groups:
- name: ./rules.conf
  rules:
  
  # - alert: HighLoad
  #   expr: avg by(system_under_test,test_environment) (system_load_average_1m) > 3
  #   for: 0s
  #   labels:
  #     severity: warning
  #   annotations:
  #     description: 'System load average > 3'
  #     summary: 'System load average > 3'
  - alert: HighGCPauseMaximum
    expr: avg by(system_under_test,test_environment) (jvm_gc_pause_seconds_max) > 50
    for: 0s
    labels:
      severity: warning
    annotations:
      description: 'GC Pause > 50 ms detected'
      summary: 'GC Pause > 50 ms detected'
  - alert: HighHeapUsage
    expr: round(100 * avg by(system_under_test, test_environment) (jvm_memory_used_bytes{area="heap"})  /  avg by(system_under_test, test_environment) (jvm_memory_max_bytes{area="heap"})) > 80
    for: 0s
    labels:
      severity: warning
    annotations:
      description: '80% of Maximum heap used'
      summary: '80% of Maximum heap used'
  - alert: ExecutorTasksQueued
    expr: avg by(system_under_test,test_environment ) (executor_queued_tasks) > 50
    for: 0s
    labels:
      severity: warning
    annotations:
      description: 'More than 50 executor tasks queued'
      summary: 'More than 50 executor tasks queued'                            
